### ISSUE TITLE
Error in topology data

### ISSUE THREAD

**Issue by tomkukral** [Mirantis/kqueen#68]
```
127.0.0.1 - - [18/Oct/2017 17:11:21] "GET /api/v1/clusters/3f4faf00-10cd-4091-9ec3-a88d3a2ec5e5/topology-data HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/tom/.venvs/kqueen/lib/python3.6/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/tom/.venvs/kqueen/lib/python3.6/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/home/tom/.venvs/kqueen/lib/python3.6/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/tom/.venvs/kqueen/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/tom/.venvs/kqueen/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/tom/.venvs/kqueen/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/tom/.venvs/kqueen/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/tom/.venvs/kqueen/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/tom/.venvs/kqueen/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/tom/.venvs/kqueen/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/tom/src/kqueen/kqueen/blueprints/api/views.py", line 94, in cluster_topology_data
    return jsonify(obj.topology_data())
  File "/home/tom/src/kqueen/kqueen/models.py", line 200, in topology_data
    'target': service_select_app_2_uid[resource['metadata']['labels']['app']]

```

**Comment by cznewt** [comment]
Fixed in #65
